spring.application.name=urbanactive
server.port=8081
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Esto crea las tablas automáticamente según tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
aemet.api-key=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZ3VzdGluLnNhbmNoZXoubWFydGluZXpAYWx1bW5vcy51cG0uZXMiLCJqdGkiOiI0MzYyZWJiMC03ZjdhLTQwOTktOGNiMS05OTcxMGM3MDgwZGYiLCJpc3MiOiJBRU1FVCIsImlhdCI6MTc3NDYzODE5MiwidXNlcklkIjoiNDM2MmViYjAtN2Y3YS00MDk5LThjYjEtOTk3MTBjNzA4MGRmIiwicm9sZSI6IiJ9.cD-ECIT6byal8YUTHEczhrCF0waIaNEQLalm9zNsS0k
openrouteservice.api-key= eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjAwMDk1MGY0ZjQ4ZTQ4MmM5NmY3NTQyZTVkMWY4ODcwIiwiaCI6Im11cm11cjY0In0=